-- NEX-094: "Fotografias privadas" — the client_photos table itself has existed since
-- 0001_initial.sql (tenant-scoped RLS already generated by the policy loop), but no
-- Storage bucket backs storage_path yet. This migration adds it.
--
-- Bucket stays private (docs/05_SECURITY_PRIVACY.md, "Uploads": bucket privado, allowlist
-- de MIME, sem SVG/executáveis) — file_size_limit/allowed_mime_types are enforced here as
-- defense in depth alongside the application-level checks in
-- src/features/clients/domain/photos.ts. The upload action always re-encodes to JPEG via
-- sharp before writing to Storage (strips EXIF, and doubles as the "verificação por
-- assinatura" — sharp rejects anything that doesn't actually decode as an image,
-- regardless of what the browser claimed as Content-Type) — so only image/jpeg ever
-- actually lands here, even though the app-level allowlist accepts a couple more input
-- formats to re-encode from.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('client-photos', 'client-photos', false, 8388608, array['image/jpeg'])
on conflict (id) do nothing;

-- Object path convention: {tenant_id}/{client_id}/{photo_id}.{ext} — storage.foldername
-- splits "name" on "/", so foldername(name)[1] is the tenant_id segment. Only that first
-- segment is checked here (not the client_id segment too) because client-level scoping is
-- already enforced by client_photos' own RLS (0001_initial.sql) on the metadata row the
-- application always writes/reads alongside the object; this policy's job is tenant
-- isolation on the Storage API itself, the same defense-in-depth split every other
-- tenant-scoped resource in this schema uses (RLS + composite FK, ADR pattern).
--
-- No update policy: a replaced photo is a delete + re-upload (a new photo_id/path), never
-- an in-place overwrite — avoids a caller silently mutating another photo's bytes at the
-- same path. No anon policy at all: this bucket is never public (docs/01_PRODUCT_REQUIREMENTS.md
-- §10, "Não existe portefólio público no MVP").
create policy client_photos_storage_select on storage.objects for select to authenticated
using (bucket_id = 'client-photos' and (storage.foldername(name))[1] = public.current_tenant_id()::text);

create policy client_photos_storage_insert on storage.objects for insert to authenticated
with check (bucket_id = 'client-photos' and (storage.foldername(name))[1] = public.current_tenant_id()::text);

create policy client_photos_storage_delete on storage.objects for delete to authenticated
using (bucket_id = 'client-photos' and (storage.foldername(name))[1] = public.current_tenant_id()::text);
